### ISSUE TITLE
Script outputting only 'a1' geometric parameter for a regular, serial 6dof industrial robot

### ISSUE THREAD

**Issue by gavanderhoorn** [JeroenDM/urdf_to_opw_kinematics#1]
Trying to run `get_yaml_from_urdf.py` on the files in [fanuc_lrmate200id_support/urdf](https://github.com/ros-industrial/fanuc_experimental/tree/b86face7a5a89ae7a04985c80af1929af39f3e77/fanuc_lrmate200id_support/urdf) (converted to `.urdf`) seems to run without errors (ignoring the 5 axis variants), but the files generated don't seem correct.

For the LR Mate 200iD/7L fi, I get:

```yaml
manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  kinematics_solver_geometric_parameters: {a1: 0.05}
  kinematics_solver_joint_offsets: [0.0, 0.0, -1.5707963267948966, -3.141592653589793,
    0.0, 0.0]
  kinematics_solver_joint_sign_corrections: [1, 1, -1, -1, -1, -1]
```

`geometric_parameters` seems to be missing the other constants.

And the values in `joint_offsets` seems shifted somehow: when I compare them to those contributed by you in ros-industrial/fanuc#284 that is.

I'm invoking the script as follows:

```
~/catkin_ws/src/urdf_to_opw_kinematics/scripts$ ./get_yaml_from_urdf.py $HOME/catkin_ws/src/fanuc_experimental/fanuc_lrmate200id_support/urdf
```

<details>
<summary>Complete console output from running the command:</summary>

```
Thanks, I received a path, I hope it is an absolute one...
/home/user/catkin_ws/src/fanuc_experimental/fanuc_lrmate200id_support/urdf
I will extract parameters from the following files:
- lrmate200id7lc.urdf
- lrmate200id4sh.urdf
- lrmate200id4s.urdf
- lrmate200id.urdf
- lrmate200id7l.urdf
- lrmate200id7h.urdf
- lrmate200id4sc.urdf
manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  kinematics_solver_geometric_parameters: {a1: 0.05}
  kinematics_solver_joint_offsets: [0.0, 0.0, -1.5707963267948966, -3.141592653589793,
    0.0, 0.0]
  kinematics_solver_joint_sign_corrections: [1, 1, -1, -1, -1, -1]

Scalar element defined multiple times: visual
Scalar element defined multiple times: collision
'fanuc_lrmate200id4sh' has 5 joints, not 6.
fanuc_lrmate200id4sh is not compatibel with opw_kinematics.
manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  kinematics_solver_geometric_parameters: {a1: 0.0}
  kinematics_solver_joint_offsets: [0.0, 0.0, -1.5707963267948966, -3.141592653589793,
    0.0, 0.0]
  kinematics_solver_joint_sign_corrections: [1, 1, -1, -1, -1, -1]

manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  kinematics_solver_geometric_parameters: {a1: 0.05}
  kinematics_solver_joint_offsets: [0.0, 0.0, -1.5707963267948966, -3.141592653589793,
    0.0, 0.0]
  kinematics_solver_joint_sign_corrections: [1, 1, -1, -1, -1, -1]

manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  kinematics_solver_geometric_parameters: {a1: 0.05}
  kinematics_solver_joint_offsets: [0.0, 0.0, -1.5707963267948966, -3.141592653589793,
    0.0, 0.0]
  kinematics_solver_joint_sign_corrections: [1, 1, -1, -1, -1, -1]

Scalar element defined multiple times: visual
Scalar element defined multiple times: collision
'fanuc_lrmate200id7h' has 5 joints, not 6.
fanuc_lrmate200id7h is not compatibel with opw_kinematics.
manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  kinematics_solver_geometric_parameters: {a1: 0.0}
  kinematics_solver_joint_offsets: [0.0, 0.0, -1.5707963267948966, -3.141592653589793,
    0.0, 0.0]
  kinematics_solver_joint_sign_corrections: [1, 1, -1, -1, -1, -1]
```

</details>

**Comment by JeroenDM** [comment]
It seems that I broke the parsing script in [this commit](https://github.com/JeroenDM/urdf_to_opw_kinematics/commit/b1bf30bbeac14b096c2ad29732a216a4bd45fac1#diff-6d7dca830631b8561fef28fba6e842b3). As you can see on [this line](https://github.com/JeroenDM/urdf_to_opw_kinematics/blob/f31eac3c2759c0fbe4c6a984e37ce6e0b8897877/scripts/get_yaml_from_urdf.py#L102), I somehow hardcoded only `a1` for testing or something.

In general, the code contains a lot of manual hardcoding fixes and quirks, I never really had the time to properly finish it :( 
(Although I still think it is a really interesting problem to solve, I should get some more people exited to work on it... :) )

**Comment by gavanderhoorn** [comment]
So would you say I shouldn't try to use this and instead do everything manually?

**Comment by JeroenDM** [comment]
I think that will be more efficient :(

**Comment by gavanderhoorn** [comment]
Ok. Thanks.

Checking some other robot models/variants, apart from the re-ordering of the `joint_offsets` parameters it seems to work.

I'll probably do a combination of manual and automated.
